export const googleMapsHaunted = [
  { elementType: 'geometry', stylers: [{ color: '#262425' }] },
  { elementType: 'labels.icon', stylers: [{ visibility: 'off' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#ffffff' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#262425' }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ color: '#484245' }] },
  { featureType: 'administrative.country', elementType: 'labels.text.fill', stylers: [{ color: '#ffffff' }] },
  { featureType: 'administrative.land_parcel', stylers: [{ visibility: 'off' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#d99a9a' }] },
  { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#a75e5e' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#2d292b' }] },
  { featureType: 'poi.park', elementType: 'labels.text.fill', stylers: [{ color: '#a75e5e' }] },
  { featureType: 'poi.park', elementType: 'labels.text.stroke', stylers: [{ color: '#262425' }] },
  { featureType: 'road', elementType: 'geometry.fill', stylers: [{ color: '#393234' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#d99a9a' }] },
  { featureType: 'road.arterial', elementType: 'geometry', stylers: [{ color: '#393133' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#3e3537' }] },
  { featureType: 'road.highway.controlled_access', elementType: 'geometry', stylers: [{ color: '#4e2e2e' }] },
  { featureType: 'road.local', elementType: 'labels.text.fill', stylers: [{ color: '#d99a9a' }] },
  { featureType: 'transit', elementType: 'labels.text.fill', stylers: [{ color: '#a75e5e' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#0e0b0d' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#914545' }] }
];

export const googleMapsDark = [
  { elementType: 'geometry', stylers: [{ color: '#18191a' }] },
  { elementType: 'labels.icon', stylers: [{ visibility: 'off' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#ffffff' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#18191a' }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ color: '#232326' }] },
  { featureType: 'administrative.country', elementType: 'labels.text.fill', stylers: [{ color: '#ffffff' }] },
  { featureType: 'administrative.land_parcel', stylers: [{ visibility: 'off' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#ffffff' }] },
  { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#ffffff' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#232326' }] },
  { featureType: 'poi.park', elementType: 'labels.text.fill', stylers: [{ color: '#ffffff' }] },
  { featureType: 'poi.park', elementType: 'labels.text.stroke', stylers: [{ color: '#18191a' }] },
  { featureType: 'road', elementType: 'geometry.fill', stylers: [{ color: '#232326' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#00FFFF' }] },
  { featureType: 'road.arterial', elementType: 'geometry', stylers: [{ color: '#232326' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#232326' }] },
  { featureType: 'road.highway.controlled_access', elementType: 'geometry', stylers: [{ color: '#232326' }] },
  { featureType: 'road.local', elementType: 'labels.text.fill', stylers: [{ color: '#00FFFF' }] },
  { featureType: 'transit', elementType: 'labels.text.fill', stylers: [{ color: '#ffffff' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#101012' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#FFFF00' }] },
  { featureType: 'water', elementType: 'labels.text.stroke', stylers: [{ color: '#FFFF00' }] }
];
