export const loadingJokes = [
  "Prometemos que não é culpa do Wi-Fi do vizinho!",
  "A fazer figas!",
  "O programador foi beber um whisky!",
  "A ligar os satélites... quase lá!",
  "A tentar convencer os servidores a colaborar",
  "A pedir ajuda ao Google Maps",
  "A desenhar mapas com lápis e papel...",
  "A perguntar ao GPS:\n“Já chegámos?”",
  "A desenhar rotas com uma caneta bic!",
  "Se não tem teia de aranha, nem vale a pena",
  "GPS diz: a recalcular. Eu digo: bora explorar!",
  "Se não for proibido entrar, nem tem piada",
  "Mapa rabiscado, coragem no bolso e o medo ficou em casa",
  "A explorar onde nem o Wi-Fi chega",
  "Se não assustar, não é urbex",
  "GPS: vire à esquerda. Eu: entrei pela janela",
  "Museu é para meninos, ruína é que é fixe",
  "Este GPS só conhece atalhos manhosos",
  "XP ganho: +10 por cada susto",
  "Sempre um passo à frente do segurança",
  "Se não tem mato, não é aventura ( ͡° ͜ʖ ͡°)",
  "A explorar onde só o vento faz check-in",
  "Mestre em encontrar entradas secretas",
  "Se não tiver perigo, não tem história",
  "Improvisar é o verdadeiro recalcular",
  "Mapa na mão, coragem no coração",
  "A cidade tem mais segredos que novelas",
  "Sempre pronto para fugir do nada",
  "GPS: sem rota.\nEu: sem medo",
  "A explorar o desconhecido desde sempre",
  "Especialista em tectos a cair",
  "A explorar porque ficar em casa é cringe",
  "GPS só serve para nos perdermos, bora pelo instinto!",
  "Se não tropeçar num tijolo, nem conta como urbex",
  "Explorar ruínas: desporto radical sem patrocínio da Red Bull",
  "Aquele momento em que o GPS desiste e tu não",
  "A entrar em sítio abandonado como quem vai ao café",
  "Explorador à séria: só corre quando ouve barulho estranho",
  "GPS: a recalcular.\nEu: a improvisar desde sempre",
  "Urbexplore na mão, mas a vibe é seguir o feeling",
  "Se não tiver história de fantasmas, nem vale a pena",
  "A explorar onde até o Google Maps tem medo de entrar",
  "À procura de sinal de vida (ou de rede)",
  "Explorar: aquele rolê que começa com 'bora?' e acaba com 'corre!'",
  "Se não tiver matagal, não tem emoção",
  "A entrar em ruína como quem entra em casa de amigo",
  "GPS: perdeu-se, mas a diversão encontrou-se",
  "Explorador urbano: só para quem não tem juízo",
  "Mapa antigo, coragem de sobra e juízo a faltar",
  "Se não sair com história para contar...",
  "A explorar onde até o GPS pede descanso",
  "Explorar: porque Netflix não tem modo aventura",
  "Se não tiver porta arrombada, não tem piada",
  "À procura de tesouro, mas só encontra tijolo e morcegos",
  "Bifinhos com cogumelos? Não, obrigado!"
];
